# $FabBSD$
# $OpenBSD: Makefile,v 1.112 2008/07/09 11:22:02 landry Exp $
# $FreeBSD: Makefile,v 1.121 1997/11/17 10:14:33 tg Exp $
     
     SUBDIR += fileutils
     SUBDIR += findutils
     SUBDIR += screen
     SUBDIR += screen,shm
     SUBDIR += screen,static
     SUBDIR += garmin-utils
     SUBDIR += gnugetopt
     SUBDIR += hfsplus
     SUBDIR += libutf8
     SUBDIR += mc
     SUBDIR += rpm

.include <bsd.port.subdir.mk>
