# $FabBSD$
# $OpenBSD: Makefile,v 1.217 2008/07/23 08:28:18 sthen Exp $
# $FreeBSD: Makefile,v 1.55 1997/11/03 12:12:27 tg Exp $

     SUBDIR += jasper
     SUBDIR += jbigkit
     SUBDIR += jpeg
     SUBDIR += netpbm
     SUBDIR += png
     SUBDIR += tiff

.include <bsd.port.subdir.mk>
