# $FabBSD$
# $OpenBSD: Makefile,v 1.42 2008/05/21 12:57:55 simon Exp $

    SUBDIR += base64
    SUBDIR += btoa
    SUBDIR += html2text
    SUBDIR += ish
    SUBDIR += libiconv
    SUBDIR += p5-Calendar-Simple
    SUBDIR += p5-Convert-ASCII-Armour
    SUBDIR += p5-Convert-ASN1
    SUBDIR += p5-Convert-BER
    SUBDIR += p5-Convert-BinHex
    SUBDIR += p5-Convert-UU
    SUBDIR += p5-Convert-UUlib
    SUBDIR += p5-DateManip
    SUBDIR += p5-IDNA-Punycode
    SUBDIR += p5-Jcode
    SUBDIR += p5-MARC-Record
    SUBDIR += p5-Net-IDN-Nameprep
    SUBDIR += p5-Text-Iconv
    SUBDIR += p5-Unicode-Map
    SUBDIR += p5-Unicode-Map8
    SUBDIR += p5-Unicode-MapUTF8
    SUBDIR += p5-Unicode-String
    SUBDIR += ppmtoTbmp
    SUBDIR += py-cjkcodecs
    SUBDIR += py-iconvcodec
    SUBDIR += recode
    SUBDIR += rpm2cpio
    SUBDIR += trans
    SUBDIR += xmltoman

.include <bsd.port.subdir.mk>
