# $FabBSD$
# $OpenBSD: Makefile,v 1.69 2008/06/14 18:32:29 eric Exp $
# $FreeBSD: Makefile,v 1.44 1997/09/13 20:19:28 chuckr Exp $
#
     SUBDIR += emacs21
     SUBDIR += emacs22
     SUBDIR += hexedit
     SUBDIR += jed
     SUBDIR += joe
     SUBDIR += jove
     SUBDIR += nano
     SUBDIR += vim

.include <bsd.port.subdir.mk>
