# $FabBSD$
# $OpenBSD: Makefile,v 1.75 2008/06/12 19:06:49 sturm Exp $

     SUBDIR += amd
     SUBDIR += blas
     SUBDIR += calc
     SUBDIR += cblas
     SUBDIR += fftw3
     SUBDIR += fftw3,float
     SUBDIR += gnuplot
     SUBDIR += lapack
     SUBDIR += octave

.include <bsd.port.subdir.mk>
