# $FabBSD$
# $OpenBSD: Makefile,v 1.202 2008/07/19 12:19:44 bluhm Exp $
# $FreeBSD: Makefile,v 1.23 1997/11/09 10:17:02 asami Exp $

     SUBDIR += libgcrypt
     SUBDIR += libgpg-error
     SUBDIR += p5-Digest-SHA1
     SUBDIR += py-crypto

.include <bsd.port.subdir.mk>
