# $FabBSD$
# $OpenBSD: Makefile,v 1.37 2007/12/10 21:24:10 eric Exp $

     SUBDIR += arc
     SUBDIR += bzip2
     SUBDIR += gtar
     SUBDIR += gtar,static
     SUBDIR += lzma
     SUBDIR += p5-Compress-Raw-Zlib
     SUBDIR += p5-Compress-Zlib
     SUBDIR += p5-IO-Compress-Base
     SUBDIR += p5-IO-Compress-Zlib
     SUBDIR += rar
     SUBDIR += unace
     SUBDIR += unrar
     SUBDIR += unzip
     SUBDIR += zip

.include <bsd.port.subdir.mk>
