# $FabBSD$
# $OpenBSD: Makefile,v 1.143 2008/07/29 00:17:16 okan Exp $
# $FreeBSD: Makefile,v 1.24 1997/10/04 23:32:05 andreas Exp $

     SUBDIR += db
     SUBDIR += dbh
     SUBDIR += gdbm
     SUBDIR += luasqlite3
     SUBDIR += mysql
     SUBDIR += p5-BerkeleyDB
     SUBDIR += p5-Class-DBI-AbstractSearch
     SUBDIR += p5-Class-DBI-Loader-Relationship
     SUBDIR += p5-Class-DBI-Pager
     SUBDIR += p5-Class-DBI-Plugin-RetrieveAll
     SUBDIR += p5-Class-DBI-Plugin-Type
     SUBDIR += p5-Class-DBI-SQLite
     SUBDIR += p5-Class-DBI-mysql
     SUBDIR += p5-Class-DBI
     SUBDIR += p5-DBD-CSV
     SUBDIR += p5-DBD-Pg
     SUBDIR += p5-DBD-SQLite
     SUBDIR += p5-DBD-SQLite2
     SUBDIR += p5-DBD-mysql
     SUBDIR += p5-DBD-mysqlPP
     SUBDIR += p5-DBI-Shell
     SUBDIR += p5-DBI
     SUBDIR += p5-Data-Page
     SUBDIR += p5-Data-Pageset
     SUBDIR += p5-GDBM_File
     SUBDIR += p5-SQL-Abstract-Limit
     SUBDIR += p5-SQL-Abstract
     SUBDIR += p5-SQL-ReservedWords
     SUBDIR += p5-SQL-Statement
     SUBDIR += p5-Sort-SQL
     SUBDIR += p5-Tie-DBI
     SUBDIR += p5-pgsql
     SUBDIR += postgresql
     SUBDIR += py-cdb
     SUBDIR += py-mysql
     SUBDIR += py-pgsql
     SUBDIR += py-psycopg,python2.4
     SUBDIR += py-psycopg,python2.5
     SUBDIR += py-psycopg2
     SUBDIR += py-pygresql
     SUBDIR += py-sqlite
     SUBDIR += py-sqlite2
     SUBDIR += qdbm
     SUBDIR += ruby-bdb
     SUBDIR += ruby-mysql
     SUBDIR += ruby-postgres
     SUBDIR += ruby-sqlite3
     SUBDIR += sqlite
     SUBDIR += sqlite3
     SUBDIR += sqlports
     SUBDIR += tdb

.include <bsd.port.subdir.mk>
