# $OpenBSD: Makefile,v 1.21 2006/11/14 14:20:03 naddy Exp $

     SUBDIR += groff
     SUBDIR += jvim
     SUBDIR += kakasi
     SUBDIR += kbanner
     SUBDIR += less
     SUBDIR += nkf
     SUBDIR += onew

.include <bsd.port.subdir.mk>
