# $OpenBSD: Makefile,v 1.84 2008/06/17 22:32:07 bernd Exp $
# $FreeBSD: Makefile,v 1.89 1997/11/24 09:24:06 tg Exp $
#

     SUBDIR += clisp
     SUBDIR += ecl
     SUBDIR += erlang
     SUBDIR += expect
     SUBDIR += gawk
     SUBDIR += ghc
     SUBDIR += guile
     SUBDIR += intel2gas
     SUBDIR += lua
     SUBDIR += mawk
     SUBDIR += open-cobol
     SUBDIR += pfe
     SUBDIR += python
     SUBDIR += ruby
     SUBDIR += sbcl
     SUBDIR += scheme-report
     SUBDIR += scheme48
     SUBDIR += scm
     SUBDIR += tcl

.include <bsd.port.subdir.mk>
