# $OpenBSD: Makefile,v 1.45 2008/06/18 20:11:21 sturm Exp $

    SUBDIR += bochs
    SUBDIR += bochs,debug
    SUBDIR += coldfire
    SUBDIR += gxemul
    SUBDIR += kqemu

.include <bsd.port.subdir.mk>
