# $FabBSD$
# $OpenBSD: Makefile,v 1.46 2007/11/28 21:18:57 naddy Exp $
# $FreeBSD: Makefile,v 1.27 1997/11/22 14:56:56 peter Exp $

     SUBDIR += birda
     SUBDIR += bottlerocket
     SUBDIR += c3270
     SUBDIR += colrdx
     SUBDIR += conserver
     SUBDIR += flipit
     SUBDIR += hamlib
     SUBDIR += kermit
     SUBDIR += libmal
     SUBDIR += lrzsz
     SUBDIR += minicom
     SUBDIR += obexftp
     SUBDIR += openobex
     SUBDIR += p5-Device-Gsm
     SUBDIR += p5-Device-Modem
     SUBDIR += p5-Device-SerialPort
     SUBDIR += pilot-link
     SUBDIR += qpage
     SUBDIR += scmxx
     SUBDIR += smstools
     SUBDIR += sredird
     SUBDIR += wy60
     SUBDIR += zmtx-zmrx

.include <bsd.port.subdir.mk>
