# $FabBSD$
# $OpenBSD: Makefile,v 1.238 2008/07/21 12:44:47 bernd Exp $
# $FreeBSD: Makefile,v 1.15 1997/11/22 00:31:24 jseger Exp $

     SUBDIR += docbook
     SUBDIR += docbook-dsssl
     SUBDIR += docbook-xsl
     SUBDIR += gdiff
     SUBDIR += gsed
     SUBDIR += iso8879
     SUBDIR += libxml
     SUBDIR += libxml1
     SUBDIR += libxslt
     SUBDIR += p5-Lingua-EN-Inflect
     SUBDIR += p5-PPI
     SUBDIR += p5-Pod-Escapes
     SUBDIR += p5-Pod-Simple
     SUBDIR += p5-Text-CSV_XS
     SUBDIR += p5-Text-Reform
     SUBDIR += textutils

.include <bsd.port.subdir.mk>
