# $FabBSD$
# $OpenBSD: Makefile,v 1.157 2008/06/20 06:04:24 ckuethe Exp $
# $FreeBSD: Makefile,v 1.26 1997/11/20 08:58:51 tg Exp $

     SUBDIR += colorls
     SUBDIR += colortail
     SUBDIR += pstree
     SUBDIR += ggrep
     SUBDIR += multitail
     SUBDIR += pciutils
     SUBDIR += skill
     SUBDIR += smartmontools
     SUBDIR += tree
     SUBDIR += usbutil

.include <bsd.port.subdir.mk>
