# $FabBSD$
# $OpenBSD: Makefile,v 1.535 2008/07/27 21:32:28 sthen Exp $
# $FreeBSD: Makefile,v 1.129 1997/11/20 13:47:40 itojun Exp $

     SUBDIR += curl
     SUBDIR += neon
     SUBDIR += p5-Net-Daemon
     SUBDIR += p5-Net-MySQL
     SUBDIR += p5-PlRPC
     SUBDIR += wget

.include <bsd.port.subdir.mk>
